### ISSUE TITLE
add url to get active routerLink

### ISSUE THREAD

**Issue by getlabs-sean** [Jakob-em/storybook-addon-angular-router#11]
I have an expanding menu component and expands the active menu by checking the router.url in order to open the menu depending on where you are in the router link. 

Just wondering it's possible to add the url to the ActionLoggingRouter:

```
get url() {
    return this.activePath;
  }
```

**Comment by Jakob-em** [comment]
Thanks for the suggestion, this definitely makes sense.
I will add this to the ActionLoggingRouter.

In the future I will try to reimplement the mocked router by reusing the regular angular router to enable also the proper handling of activated routes (as suggested in #8) but for now returning the activePath should be good enough.

**Comment by Jakob-em** [comment]
Included with version 1.5.0
