### ISSUE TITLE
Angular v14 support

### ISSUE THREAD

**Issue by Endrzei** [Jakob-em/storybook-addon-angular-router#13]
Hi,

First of all thanks for the awesome package!

Since Angular v14 is out, could we please have support for it?

**Comment by Jakob-em** [comment]
Sure! I will have a look at it

**Comment by Jakob-em** [comment]
I just releases version 1.6.0 which should work with angular 14 @Endrzei. Feel free to reopen the issue if you experience any problems with angular 14 and the plugin.
