### ISSUE TITLE
Use the new Framework API?

### ISSUE THREAD

**Issue by jonniebigodes** [Jakob-em/storybook-addon-angular-router#18]
Hey @Jakob-em!
I'm one of the Storybook maintainers. I focus primarily on documentation and community outreach. I'm opening up this issue and letting you know that the Storybook API for building addons is currently being updated to factor in the changes introduced by the upcoming 7.0 release. If you're interested in making the required changes to help the community from benefiting from using your addon, we've prepared an abridged guide for the required changes [here](https://chromatic-ui.notion.site/Addon-migration-for-Storybook-7-002f2f627c1d470298ca94894ab8a040), and if you have any questions or issues, please reach out to us in the #prerelease channel in our [Discord Server](https://discord.gg/storybook). 

Hope you have a great day!

Stay safe

**Comment by Jakob-em** [comment]
Hi @jonniebigodes, thanks for the heads up!
I just upgraded to the v7 beta on the next branch, adjusted a few small things and pushed a prerelease. Looks like everything is working great with storybook v7 and my plugin 👍🏻

**Comment by jonniebigodes** [comment]
@Jakob-em thanks for following up with me on this, glad that everything is already being already working with the new API, should any issue arise, don't hesitate to reach out to us via our Discord Server or the issue tracker.

Hope you have a great day.

Stay safe

**Comment by JReinhold** [comment]
Hey @Jakob-em, Storybook v7.0.0 is out! It's only on the `next` tag for now, but it's still targetable with the `^7.0.0` semver range, so you should be able to develop against it with no dependency issues.

You should be able now to change the Storybook dependencies to a bare `^7.0.0` and release a stable version.

If you hit any issues with v7, we've written a migration guide for addon authors [here](https://github.com/storybookjs/storybook/blob/norbert/add-addon-migration-guide/MIGRATION.md?rgh-link-date=2023-03-31T20%3A36%3A23Z#specific-instructions-for-addon-creators) and [here](https://chromatic-ui.notion.site/Addon-migration-for-Storybook-7-002f2f627c1d470298ca94894ab8a040).

You're also free to reach out to us in the #prerelease channel on our [Discord Server](https://discord.gg/storybook) and we'll happily help you out!

cc @ndelangen

**Comment by Jakob-em** [comment]
@JReinhold Great! I just released v1.8.0 which is compatible with storybook ^7.0.0
