### ISSUE TITLE
`router.isActive()` does not work

### ISSUE THREAD

**Issue by sonallux** [Jakob-em/storybook-addon-angular-router#24]
The [`isActive()`](https://angular.io/api/router/Router#isactive) Method of the `Router` has some overloads. Unfortunatly only the overload `isActive(url: UrlTree, exact: boolean)` is supported by this addon.

The other overloads `isActive(url: string | UrlTree, matchOptions: IsActiveMatchOptions)` is not working when using this addon. To make matters worse the `isActive(url: UrlTree, exact: boolean)` signature has been deprecated in the Router API.

Could you please also provide an implementation for the other overloads of `isActive()`?

**Comment by Jakob-em** [comment]
Hi, thanks for raising this. I will look into adding the missing overloads.

**Comment by Jakob-em** [comment]
I released a canary version `1.9.2--canary.25.f96e573.0` with a fix for the issue. Let me know if it works now for you

**Comment by sonallux** [comment]
> @sonallux I released a canary version `1.9.2--canary.25.f96e573.0` with a fix for the issue. Let me know if it works now for you

 @Jakob-em Thanks for the fix :+1:  It works perfectly and sorry for the late reply. I was busy with other things.
