### ISSUE TITLE
Getting error: TypeError: HD.addons.register is not a function

### ISSUE THREAD

**Issue by awaragi** [Jakob-em/storybook-addon-angular-router#29]
Angular project running 17.1.3. Storybook 8.0.9 and storybook-addon-angular-router 1.10.0

A simple component which requires RouterLink injection. The component story works but I get this non blocking error in the console.

![image](https://github.com/Jakob-em/storybook-addon-angular-router/assets/24778363/5dac103b-b79e-4257-8e08-d74e7703c52c)

**Comment by EliezerB123** [comment]
+1

> "@angular/core": "^15.2.9"
> "@storybook/angular": "^8.1.4"
> "storybook-addon-angular-router": "^1.10.0"

I'm having the exact same error, "HD.addons.register is not a function".

**Comment by dcbeck** [comment]
Having the same issue with angular 18.0.4 and storybook 8.1.11
